general:
  username: "omidshabab"
  email: "hey@omidshabab.com"

en:
  name: "Omid Shabab"
  desc: "Publish Any Posts on Your Own Server. Open-Source, Self-hosted, no license required, built for both humans and AI Agents."
